const products = [
  {
    id: '1',
    title: 'Wireless Bluetooth Headphones',
    description: 'Noise cancelling over-ear headphones with long battery life.',
    price: 2999,
    image: 'https://via.placeholder.com/150?text=Headphones',
    category: 'Electronics',
    inStock: true,
    rating: 4.5,
  },
  {
    id: '2',
    title: 'Casual Men’s Sneakers',
    description: 'Comfortable and stylish sneakers for everyday use.',
    price: 1999,
    image: 'https://via.placeholder.com/150?text=Sneakers',
    category: 'Fashion',
    inStock: true,
    rating: 4.2,
  },
  {
    id: '3',
    title: 'Stainless Steel Water Bottle',
    description: 'Insulated water bottle that keeps drinks cold for 24 hours.',
    price: 499,
    image: 'https://via.placeholder.com/150?text=Bottle',
    category: 'Home & Kitchen',
    inStock: true,
    rating: 4.8,
  },
  {
    id: '4',
    title: 'Smart LED TV 42 inch',
    description: 'Full HD Smart LED TV with built-in streaming apps.',
    price: 23999,
    image: 'https://via.placeholder.com/150?text=LED+TV',
    category: 'Electronics',
    inStock: false,
    rating: 4.3,
  },
  {
    id: '5',
    title: 'Leather Office Bag',
    description: 'Premium leather laptop bag with multiple compartments.',
    price: 1499,
    image: 'https://via.placeholder.com/150?text=Office+Bag',
    category: 'Accessories',
    inStock: true,
    rating: 4.0,
  },
  {
    id: '6',
    title: 'Digital Wrist Watch',
    description: 'Water-resistant digital watch with alarm and stopwatch.',
    price: 999,
    image: 'https://via.placeholder.com/150?text=Watch',
    category: 'Fashion',
    inStock: true,
    rating: 3.9,
  },
];

export default products;
